### PR TITLE
Better website (again)

### PR DESCRIPTION
**Pull request by TheBITLINK**
I need to learn git, shit

### CODE REVIEW

**Comment by Rabrennie** [comment]
Nice! thanks :+1:

**Comment by Rabrennie** [comment]
Dude this looks amazing! Thank you so much

**Comment by graypegg** [comment]
it looks so cool, until you run 

``` javascript
Δ.johnCena()
```

on the playground :P

**Comment by TheBITLINK** [comment]
KEK I have missed a lot

Should i make the playground sandboxed?

**Comment by graypegg** [comment]
I vote no, I love it how it is :p

**Pull request merged**
