### PR TITLE
Better website

### PR DESCRIPTION
**Pull request by TheBITLINK**
aesthetics

### CODE REVIEW

**Comment by Rabrennie** [comment]
You'll want to merge it into master.

**Comment by TheBITLINK** [comment]
How? i'm still new at GitHub

Do i need to make another pull request?

**Comment by graypegg** [comment]
Yep, but before you make a new one, run

```
git fetch upstream
git merge upstream/master
```

considering you called the original repo "upstream"

**Comment by Rabrennie** [comment]
If you don't have upstream check https://help.github.com/articles/configuring-a-remote-for-a-fork/ this out

**Comment by graypegg** [comment]
Holy crap, I just cloned your repo, that's look so nice

**Pull request closed without merging**
