### PR TITLE
create bestCSS

### PR DESCRIPTION
**Pull request by seiyria**
it's beautiful now

### CODE REVIEW

**Comment by gytdau** [comment]
You beautified it but this is still not original code.

I mean:
`var e, s, m, h, v, c, b, g, p, f, x, N, U, w, y, k, z, M, j, F, $, q, G, E, T, B, C, H, L, S, A, D, I;`

There's no way these are the actual variable names used. Do you not have the original code anymore?

**Comment by seiyria** [comment]
I just beautified the code from the bookmarklet via our overlord: http://rabrennie.com/BestCSS/

Guess I could have actually grabbed the code from the repo but ¯\_(ツ)_/¯

What happened to accepting everything?

**Comment by gytdau** [comment]
I don't know. There were talks of forcing JSDocs on all code so I think our standards are slowly increasing.

But this doesn't technically violate any rules, I guess, so I'll merge it for now and let someone else deal with it later.

**Comment by seiyria** [comment]
That's the spirit! :+1: 

You can still have JSDocs and still maintain the ridiculousness that is this repo. The only difference is that the ridiculousness will be better documented.

**Pull request merged**
