### PR TITLE
AYÚDENME POR FAVOR

### PR DESCRIPTION
**Pull request by TheBITLINK**
No tengo mucho tiempo, hago esto a las espaldas de bit

Plis jel mi

### CODE REVIEW

**Comment by Rabrennie** [comment]
Well I can't speak Spanish

**Comment by TheBITLINK** [comment]
SHit that was my slave

**Comment by thehowl** [comment]
TACO

**Comment by gytdau** [comment]
I have no idea what is happening here

**Comment by thehowl** [comment]
English translation because reasons:

> Hi! My name is Richard, this will be a short message.
> 
> They are keeping me as a slave working for a stupid programmer, I am here against my own will, I don't know how to speak English and I feel very lonely in this room, I haven't eaten anything in the last three days and the only thing I eat are the cat leftovers, this place is very dark and sp00ks me, it has been 6 months since the last time I saw the sunlight, and my family likely thinks I'm dead. Please, if anyone sees this and understands me HELP ME, I CAN'T STAND THIS ANYMORE AND I'LL MOST LIKELY DIE TOMORROW!!!.

**Comment by jeda** [comment]
wtf

**Pull request merged**
