### PR TITLE
Added to Contributors

### PR DESCRIPTION
**Pull request by SCKelemen**
If this is a sinking ship, I'm going down with ye, mateys!

### CODE REVIEW

**Comment by ghost** [comment]
Hey, is there any **Anything.js** script that is written in **NodeJS**?
cc @Rabrennie

**Comment by Rabrennie** [comment]
@christoga I'm not sure I understand the question?

**Comment by ghost** [comment]
The question is:
NodeJS is basically JS but for the server-side, the question was: if I can actually run Anything.js in NodeJS

**Comment by Rabrennie** [comment]
You would need to modify it as it was designed to be used in a browser. It relies on window which nodejs doesn't support.

Most of the scripts in it are DOM based anyway.

**Comment by TheBITLINK** [comment]
Also that's the reason why this isn't on NPM

**Comment by Rabrennie** [comment]
We could export it as a module and have a separate one but then most of the scripts wouldn't even work anyway

**Comment by ghost** [comment]
Oh ok.

**Pull request merged**
