### PR TITLE
Accuratly adds some numbers

### PR DESCRIPTION
**Pull request by graypegg**
Idea from ju57u5 on IRC

### CODE REVIEW

**Comment by gytdau** [comment]
Please create your own file in the `src` folder - your changes will be overwritten every time the distribution is generated.

**Comment by gytdau** [comment]
Goddamnit. I should really look more before commenting. Sorry.

**Comment by graypegg** [comment]
no worries, sorry it can't be merged, forgot to pull from upstream

**Comment by Rabrennie** [comment]
It's alright it shouldn't be too hard to merge it.

**Comment by Rabrennie** [comment]
fixed

**Pull request closed without merging**
