### PR TITLE
Add `SongThatShouldHaveNeverStarted` functionality

### PR DESCRIPTION
**Pull request by vccortez**
I might rewatch The Office.

### CODE REVIEW

**Comment by ghost** [comment]
I still hasn't get it, is this project going to end?

**Comment by TheBITLINK** [comment]
shh

**Comment by vccortez** [comment]
@christoga It's only going to end when I get more commits than @Rabrennie

**Comment by ghost** [comment]
Jeez, I thought it was actually going to end, thank's for telling me dude @vekat

**Comment by ghost** [comment]
By the way, does all this PR's.
Does everyone actually just make a random PR to reach 1,100/2,000 commits?

I've seen many of useless PR's this month. 
_even though the point of this javascript framework is useless_

**Pull request merged**
