### PR TITLE
Uptime funk, and many other things.

### PR DESCRIPTION
**Pull request by thehowl**
Comes with:
- a fix for the disaster @montanaflynn did (which broke the build).
- various dist updates
- a function to push to the screen the best video of all time
- this function also allows to push your own video on top of the screen
- the video loops! (should)
- gulp-jsfuck require moved to inside the job itself, so that it isn't unnecessarily required.

### CODE REVIEW

**Comment by gytdau** [comment]
Oh, wow. I wasn't aware of the build being broken. Which commit was the one that broke it?

**Comment by thehowl** [comment]
b32b574

**Comment by gytdau** [comment]
Thanks.

**Comment by gytdau** [comment]
I'll make sure to check if all the code that's being comitted doesn't produce any errors from now on :)

**Comment by montanaflynn** [comment]
:shame:

But really, it should be automated. If we used mocha & travisCI even without writing tests I think it would catch breaking builds. This is why I didn't want to copy + paste functions from other packages I already have created with 100% test coverage...

**Pull request merged**
