### PR TITLE
efficientSort

### PR DESCRIPTION
**Pull request by tojba**
This will sometimes sort within 1 try.

### CODE REVIEW

**Comment by gytdau** [comment]
This is brilliant.

**Comment by dstrekelj** [comment]
While I do love bogosort, it's dangerously close to breaking the first rule of contributing (nothing that'll crash a web page). The while loop can easily block the thread for even a smaller amount of array elements, rendering the entire thing unresponsive. More often than not, this will lead to termination (voluntary or involuntary) of the browser window or tab.

I'm not sure how close we should stick to the rules, though, so it's questionable whether this even warrants a discussion.

**Comment by Rabrennie** [comment]
@dstrekelj it's only really a worry if something blocks by default when anything.js is loaded.

**Comment by dstrekelj** [comment]
@Rabrennie Gotcha! I'll keep that in mind.

**Pull request merged**
