### PR TITLE
Grammar Fixes

### PR DESCRIPTION
**Pull request by SCKelemen**

### CODE REVIEW

**Comment by TheBITLINK** [comment]
Idk about this one...

**Comment by SCKelemen** [comment]
It's literally the same thing, but implemented in one line with less memory use.

**Comment by vccortez** [comment]
I think you missed the point, that code was shitty on purpose.

**Comment by TheBITLINK** [comment]
^

**Comment by TheBITLINK** [comment]
I request the presence of the allmighty @Rabrennie

**Comment by Rabrennie** [comment]
is ok

**Comment by ghost** [comment]
Thinking about making tons of real songs lyrics? cool?

**Comment by TheBITLINK** [comment]
Cool as hell

mumble-2016-06-06-220006

**Pull request merged**
