### PR TITLE
Added logo

### PR DESCRIPTION
**Pull request by gytdau**
This took me all of five minutes to make so if you reject this I will be deeply saddened

### CODE REVIEW

**Comment by TheBITLINK** [comment]
At this rate, this will end up being a serious project

**Comment by gytdau** [comment]
A serious- _ly fantastic_ - project, you mean.

**Comment by mobeigi** [comment]
Someone make an API!

**Comment by gytdau** [comment]
I'll get to work on the marketing material!

**Comment by TheBITLINK** [comment]
When i come back to home, i'll continue adding more shit

We should document it as well...

btw http://thebitlink.github.io/anything.js/

**Comment by gytdau** [comment]
That's actually really cool, @TheBITLINK 

Oh boy, this project will make my GitHub contribution graph go nuts

**Comment by TheBITLINK** [comment]
I'll make a better website later, i'll use your logo

**Comment by Rabrennie** [comment]
Thanks for the logo. Looks awesome.

It's already a serious project hahaha.

**Pull request merged**
