### PR TITLE
add Console.log()

### PR DESCRIPTION
**Pull request by charmaine**

### CODE REVIEW

**Comment by gytdau** [comment]
Thank you for your help in making anything.js great again. Everyone tells me that anything.js has the best functions around. No functions are better than the functions in anything.js.

**Comment by charmaine** [comment]
No problem & thanks for merging my pull request! It was definitely a fun little first project to contribute to. :)

**Comment by TheBITLINK** [comment]
I've just realized this is PR #420

**Comment by gytdau** [comment]
Well shit that didn't work.

**Comment by gytdau** [comment]
Fixed it.

**Comment by Rabrennie** [comment]
Heh

**Comment by TheBITLINK** [comment]
blaeitz indeed

**Pull request merged**
