### PR TITLE
Better zombofy

### PR DESCRIPTION
**Pull request by graypegg**
Now plays the Zombo.com "music", and is fixed on the screen. jQuery is loaded in dynamically.

### CODE REVIEW

**Comment by Rabrennie** [comment]
jQuery
no-power

**Comment by graypegg** [comment]
https://github.com/Rabrennie/anything.js/blob/master/src/addRealFunctionalityOnTheFly.js

;)

(Who ever made the zombofy function used jQuery, don't blame me :P)

**Comment by Rabrennie** [comment]
I didn't even notice that before.

**Comment by Rabrennie** [comment]
Music doesn't seem to work. Would be better if you loaded it in dynamically tbh

**Comment by graypegg** [comment]
Hmm, was worried about that, base64 urls have some limits on them i think? works in FF, but i'll see if i can host it somewhere

**Comment by Rabrennie** [comment]
it takes up 2mb like that. A pretty big js file haha

**Pull request merged**
