### PR TITLE
shit ass devs need to be put in line

### PR DESCRIPTION
**Pull request by jbhamilton**
Shun the project developers with hateful messages to really get them motivated.

### CODE REVIEW

**Comment by Rabrennie** [comment]
I feel so motivated right now

**Comment by Rabrennie** [comment]
This is actually fantastic.

**Comment by jbhamilton** [comment]
Haha thanks, saw your post on Reddit figured wtf I'll add to the madness hahaha.

**Comment by Rabrennie** [comment]
You have killed me with "You would be better off trying to read brail than this code"

**Comment by jbhamilton** [comment]
Yeah, thats a true insult!

**Pull request merged**
