### PR TITLE
Fix missing email domain

### PR DESCRIPTION
**Pull request by vccortez**
How else am I supposed to receive money offers from a Nigerian Prince and penis enlarging tools if I don't type my e-mail everywhere?

### CODE REVIEW

**Comment by Rabrennie** [comment]
does the + in gmail send it to a new folder?

**Comment by vccortez** [comment]
Yes, you can create a custom label based on that version of your email address.

**Comment by ghost** [comment]
Thank's for the tips!

**Comment by TheBITLINK** [comment]
I didn't know that

Sadly, it's 2expensiv4me to use gmail with my domain 😢

**Pull request merged**
