### PR TITLE
Revert "Rename !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!…"

### PR DESCRIPTION
**Pull request by Rabrennie**
Reverts Rabrennie/anything.js#154

Filename too long

### CODE REVIEW

**Comment by inderps** [comment]
but it was intentional ;-(

**Comment by Rabrennie** [comment]
git on my machine doesn't like it

**Comment by inderps** [comment]
github can accept upto 1000 characters file name. How much is your limit? I will rename it to match your limit then

**Comment by Rabrennie** [comment]
maybe it was gulp? either way something didn't like it. 

I don't know the limit sorry.

**Comment by gytdau** [comment]
If there's a limit... then there must be a string that's the most perfect name to be on top... meaning Github will have to sort two file names that are equally perfect by _time they were comitted_...

The race is on, gentlemen.

**Pull request merged**
