### PR TITLE
Song that never ends

### PR DESCRIPTION
**Pull request by dylanrees**

### CODE REVIEW

**Comment by gytdau** [comment]
Catchy. This pull request doesn't add the file, though, since you deleted it in the most recent commit.

Also, this is considered to go against rule 1. To fix this, there's two options:
1. Make the song repeat a finite number of times (e.g. 500)
2. Add some delay by making a recursive setTimeout function

Option 2 is cooler, but Option 1 is way easier. You can choose whichever.

**Comment by dylanrees** [comment]
Duh, oops.  I'll change that and re-submit.

**Comment by gytdau** [comment]
You didn't have to close this pull request - any commits you add to the branch will be automatically added to this pull request. But it's OK, no big deal :smile:

**Comment by dylanrees** [comment]
Hmm... ok, so I'm still learning here.

1.) Are you saying the function can't call an arbitrary integer as an argument and repeat that many times because of rule 1?  Or is the fact that it repeats infinitely for i<0 the problem?

2.) You're saying I deleted the file but in my branch I see that  src/SongThatNeverEnds.js is present.  Did I do something wrong?

**Comment by thehowl** [comment]
@gytdau afaik, Rabrennie said that rule 1 applies only in case the function runs each time the script is included, which does not happen in this case.

**Comment by Rabrennie** [comment]
giphy 1

**Comment by thehowl** [comment]
thanks mighty lord and saviour Rabrennie

**Comment by dylanrees** [comment]
Solid.

**Pull request merged**
